mongo-url = "mongodb://root:vnzcFLZ5Y5uVUK3Y@<your-mongo>/admin?replicaSet=mgset-17327671"
redis-url = "redis://:gzd4attDAzmG5O6EgsmCbHbUxqUOKY@<your-redis>:6379/0"

direct-read-namespaces =["fm-prod.page_section"]
change-stream-namespaces =["fm-prod.page_section"]
stats = true
dropped-collections = false
dropped-databases = false
resume = true
resume-write-unsafe = true
resume-name = "default"
resume-strategy = 0
index-as-update = true
#cluster-name = 'r-2ze1pzswz2kydk10k5-content-zone'
exit-after-direct-reads = false

[[mapping]]
namespace = "fm-prod.page_section"
index = "fm-prod.page_section"
command = "SADD"
key = "{{.cp_vid}}"
val = "{{ toJson . }}"

[[filter]]
namespace = "fm-prod.page_section"
script = """
module.exports = function(doc) {
    return ["00084100dab811eaabb05b00ec2234fc"].indexOf(doc._id) != -1
}
"""

[[script]]
namespace = "fm-prod.page_section"
script = """
module.exports = function(doc) {
    console.log(JSON.stringify(doc))
    return false
}
"""

[[relate]]
namespace = "fm-prod.page_section" # when a state changes trigger a thing change event since thing is associated to a state
with-namespace = "fm-prod.kkk"
src-field = "items.id" # use the _id field of the state that changed to lookup associated things
match-field = "_id" # only trigger change events for the things where thing.s (match-field) = state._id (src-field).
#keep-src = false
max-depth=3
dot-notation = true
#
#[[relate]]
#namespace = "fm-prod.page_section" # when a state changes trigger a thing change event since thing is associated to a state
#with-namespace = "fm-prod.ddd"
#src-field = "items.id" # use the _id field of the state that changed to lookup associated things
#match-field = "_id" # only trigger change events for the things where thing.s (match-field) = state._id (src-field).
##keep-src = false
#dot-notation = true
#
#[[mapping]]
#namespace = "fm-prod.ddd"
#index = "fm-prod.ddd"
#command = "SADD"
#key = "{{.cp_vid}}"
#val = "{{ toJson . }}"
#
#[[script]]
#namespace = "fm-prod.ddd"
#script = """
#module.exports = function(doc) {
#    console.log("ddddd",JSON.stringify(doc))
#    return false;
#}
#"""

[[mapping]]
namespace = "fm-prod.kkk"
index = "fm-prod.kkk"
command = "SADD"
key = "{{.cp_vid}}"
val = "{{ toJson . }}"


[[script]]
namespace = "fm-prod.kkk"
script = """
module.exports = function(doc) {

    console.log("kkkkk",doc._id,doc.title_cn)
    return false;
}
"""


